on:
  push:
    branches:
      - main
      - develop
      - release
      - release/**
      - fiber-v8

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ['20.x', '22.x']
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - run: npx nx build-libs

      - run: npx nx build-storybook
